services:
  market-producer:
    build: ./producers
    command: ["python", "/app/yf_producer.py"]
    env_file: .env
    volumes:
      - ./certs:/app/certs:ro
      - ./.env:/app/.env:ro
    
  news-producer:
    build: ./producers
    command: ["python", "/app/news_producer.py"]
    env_file: .env
    volumes:
      - ./certs:/app/certs:ro
      - ./.env:/app/.env:ro

  simulated-reddit-producer:
    build: ./producers
    command: ["python", "/app/simulated_reddit_producer.py"]
    env_file: .env
    volumes:
      - ./certs:/app/certs:ro
      - ./.env:/app/.env:ro
      - ./producers/data:/app/data:ro

  bronze-processor:
    build: 
      context: ./processors
    command: ["bronze_layer.py"]
    env_file: .env
    volumes:
      - ./processors/bronze_layer:/app/processor
      - ./certs:/app/certs:ro

  silver-processor:
    build: 
      context: ./processors
    command: ["silver_layer.py"]
    env_file: .env
    volumes:
      - ./processors/silver_layer:/app/processor
      - ./certs:/app/certs:ro
    depends_on:
      - bronze-processor

  gold-processor:
    build: 
      context: ./processors
    command: ["gold_layer.py"]
    env_file: .env
    volumes:
      - ./processors/gold_layer:/app/processor
      - ./certs:/app/certs:ro
    depends_on:
      - silver-processor